
name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: build web
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt-get -y update
        git clone https://gitlab.gnome.org/GNOME/epiphany.git
        cd epiphany
        sudo apt-get build-dep -y epiphany-browser 
        mkdir build && cd build
        meson ..
        ninja
        sudo ninja install

