
name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    container: fedora:rawhide
    steps:
    - uses: actions/checkout@v2
    - name: build web
      run: |
        dnf -y install wget git
        dnf -y install 'dnf-command(builddep)'
        wget https://download-ib01.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/source/tree/Packages/e/epiphany-3.37.1-3.fc33.src.rpm  
        dnf -y builddep epiphany-3.37.1-3.fc33.src.rpm 
        git clone https://gitlab.gnome.org/GNOME/epiphany.git
        cd epiphany
        mkdir build && cd build
        meson ..
        ninja
        sudo ninja install

