
name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build vscode
      run: |
        git clone https://github.com/Microsoft/vscode/
        cd vscode
        yarn
