
name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    container: fwilhe/dev
    steps:
    - uses: actions/checkout@v2
    - name: build web
      run: |
        git clone https://gitlab.gnome.org/GNOME/epiphany.git
        dnf -y install 'pkgconfig(hogweed)'
        cd epiphany
        mkdir build && cd build
        meson ..
        ninja
        sudo ninja install

